version: '3.8'

services:
    backend:
        image: allora-monitor-backend:latest # 이미지 이름 지정
        build:
            context: ./backend
            dockerfile: Dockerfile
        # container_name: allora-monitor-backend  # 레플리카 사용시 고정 이름 사용 불가
        volumes:
            - allora_monitor_data:/app/data
        ports:
            - '5001:8080' # 호스트의 5001 포트를 컨테이너의 8080 포트에 매핑
        restart: unless-stopped
        networks:
            - allora-web-network
        deploy:
            mode: replicated
            replicas: 2 # 원하는 레플리카 수
            restart_policy:
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 10s
                order: start-first
            endpoint_mode: dnsrr # DNS 라운드 로빈 사용

    frontend:
        image: allora-monitor-frontend:latest # 이미지 이름 지정
        build:
            context: ./temp-next-app
            dockerfile: Dockerfile
        # container_name: allora-monitor-frontend  # 레플리카 사용시 고정 이름 사용 불가
        depends_on:
            - backend
        ports:
            - '5000:3000' # 호스트의 5000 포트를 컨테이너의 3000 포트에 매핑
        environment:
            # 클라이언트는 /api로 접근, 서버는 내부에서 프록시
            - NEXT_PUBLIC_API_URL=/api
            # Next.js 내부 프록시용 백엔드 주소
            - BACKEND_URL=http://backend:8080
        restart: unless-stopped
        networks:
            - allora-web-network
        deploy:
            mode: replicated
            replicas: 3 # 원하는 레플리카 수
            restart_policy:
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 10s
                order: start-first
            endpoint_mode: dnsrr # DNS 라운드 로빈 사용

networks:
    allora-web-network:
        external: true
        name: allora-web-network

volumes:
    allora_monitor_data:
        # Using a named volume for data persistence
        # This will persist even if containers are removed
