version: '3.8'

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: allora-monitor-backend
        volumes:
            - ./backend/data:/app/data
        restart: unless-stopped
        networks:
            - allora-web-network

    frontend:
        build:
            context: ./temp-next-app
            dockerfile: Dockerfile
        container_name: allora-monitor-frontend
        depends_on:
            - backend
        environment:
            - NEXT_PUBLIC_API_URL=/api
        restart: unless-stopped
        networks:
            - allora-web-network

    nginx:
        image: nginx:alpine
        container_name: allora-monitor-nginx
        ports:
            - '280:280'
            - '2443:2443'
        volumes:
            - ./nginx/conf:/etc/nginx/conf.d
        depends_on:
            - frontend
            - backend
        restart: unless-stopped
        networks:
            - allora-web-network

networks:
    allora-web-network:
        driver: bridge
