version: '3.8'

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: allora-monitor-backend
        volumes:
            - ./backend/data:/app/data
        restart: unless-stopped
        networks:
            - allora-web-network

    frontend:
        build:
            context: ./temp-next-app
            dockerfile: Dockerfile
        container_name: allora-monitor-frontend
        depends_on:
            - backend
        environment:
            - NEXT_PUBLIC_API_URL=/api
        restart: unless-stopped
        networks:
            - allora-web-network

    caddy:
        image: caddy:2-alpine
        container_name: allora-monitor-caddy
        ports:
            - '280:80'
            - '2443:443'
        volumes:
            - ./caddy/Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config
        depends_on:
            - frontend
            - backend
        restart: unless-stopped
        networks:
            - allora-web-network

networks:
    allora-web-network:
        driver: bridge

volumes:
    caddy_data:
    caddy_config:
