version: '3.8'

services:
    backend:
        image: allora-monitor-backend:latest # 이미지 이름 지정
        build:
            context: ./backend
            dockerfile: Dockerfile
        # container_name: allora-monitor-backend  # 레플리카 사용시 고정 이름 사용 불가
        volumes:
            - allora_monitor_data:/app/data
        restart: unless-stopped
        networks:
            - allora-web-network
        deploy:
            mode: replicated
            replicas: 2 # 원하는 레플리카 수
            restart_policy:
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 10s
                order: start-first

    frontend:
        image: allora-monitor-frontend:latest # 이미지 이름 지정
        build:
            context: ./temp-next-app
            dockerfile: Dockerfile
        # container_name: allora-monitor-frontend  # 레플리카 사용시 고정 이름 사용 불가
        depends_on:
            - backend
        environment:
            - NEXT_PUBLIC_API_URL=/api
        restart: unless-stopped
        networks:
            - allora-web-network
        deploy:
            mode: replicated
            replicas: 3 # 원하는 레플리카 수
            restart_policy:
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 10s
                order: start-first

    nginx:
        image: nginx:alpine
        # container_name: allora-monitor-nginx  # 레플리카 사용시 고정 이름 사용 불가
        ports:
            - '280:280'
            - '2443:2443'
        volumes:
            - ./nginx/conf:/etc/nginx/conf.d
        depends_on:
            - frontend
            - backend
        restart: unless-stopped
        networks:
            - allora-web-network
        deploy:
            mode: replicated
            replicas: 1 # 로드 밸런서는 하나만 실행
            placement:
                constraints:
                    - node.role == manager # 매니저 노드에만 배포하여 포트 충돌 방지

networks:
    allora-web-network:
        external: true
        name: allora-web-network

volumes:
    allora_monitor_data:
        # Using a named volume for data persistence
        # This will persist even if containers are removed
