version: '3.8'

services:
    backend:
        image: allora-monitor-backend:latest
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - allora_monitor_data:/app/data
        ports:
            - '5001:8080'
        restart: always
        networks:
            - allora-web-network

    frontend:
        image: allora-monitor-frontend:latest
        build:
            context: ./temp-next-app
            dockerfile: Dockerfile
        depends_on:
            - backend
        ports:
            - '5000:3000'
        environment:
            - NEXT_PUBLIC_API_URL=/api
            - BACKEND_URL=http://backend:8080
        restart: always
        networks:
            - allora-web-network

networks:
    allora-web-network:
        external: true
        name: allora-web-network

volumes:
    allora_monitor_data:
        # Using a named volume for data persistence
        # This will persist even if containers are removed
